### PR TITLE
Adds z-index support

### PR DESCRIPTION
**Pull request by ajimix**
As requested in #51 this adds supports for `data-rellax-zindex`

Thanks for your great work with this project!

/cc @moeamaya you said you'll be happy to merge it 😄

### CODE REVIEW

**Comment by iapparatus** [comment]
@ajimix Thank you! This is great.

**Comment by iapparatus** [comment]
Perhaps you can also include an example.

**Comment by ajimix** [comment]
@iapparatus I've added one in the readme :)

**Comment by jalada** [comment]
Don't you need `transform-style: preserve-3d` on the parent for this to work?

**Comment by ajimix** [comment]
mmm I'm not sure. In my use-case, is working without adding it

**Comment by Hirbod** [comment]
thanks @jalada I exactly needed this

**Pull request merged**
