### PR TITLE
Fix inconsistent scrollTop calculation in Firefox

### PR DESCRIPTION
**Pull request by nlemoine**
See the pen here (in latest Chrome & Firefox): http://codepen.io/hellonico/full/ygvroX/
(Fork the pen and open it in debug mode)

### CODE REVIEW

**Comment by nlemoine** [comment]
I fixed some issues regarding elements query. 

1. [This line](https://github.com/dixonandmoe/rellax/blob/4d44858b21edf0a3ac31b2c6adaf7c8800d81525/rellax.js#L72) will always evaluate to `true` even if no element is found. 

2. [This line](https://github.com/dixonandmoe/rellax/blob/4d44858b21edf0a3ac31b2c6adaf7c8800d81525/rellax.js#L77) will not return an array but only the first DOM element met. But given the first issue above, it will never be executed. 

3. I removed `getElementsByClassName`, `querySelectorAll` has a [very decent support](https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelectorAll) now. 

I also think the script should fail silently when no element is found instead of throwing an error.

**Comment by moeamaya** [comment]
@nlemoine I really like this PR. Can also allow more than just classname as the selector!

**Comment by nlemoine** [comment]
Glad you liked it! Would you consider the last point of the last comment?

> script should fail silently when no element is found instead of throwing an error

**Comment by twiro** [comment]
Ah... great this PR made it into the main repo! Solves some bugs I had when reloading a parallaxed page in Firefox. 

But it would be great to see version numbers [making sense](http://semver.org/) after changes like these... just noticed everything is still "1.0.0". Will post a separate issue for that!

**Comment by moeamaya** [comment]
@twiro thx for the feedback. I don't push anything to NPM or update the README until I've seen enough users test the new code and report no bugs. Our process is to trust PRs and merge them, then allow the community to validate the quality.

But we'd love your help if you're up for helping us organize versions and merged PRs!! At the moment, we've run through all the code to 1.0.0 but any subsequent work is still only mildly tested.

**Comment by nlemoine** [comment]
@twiro You can still use this workaround in your package.json:
```json
{
  "rellax": "git+https://git@github.com/dixonandmoe/rellax.git",
}
```
But I agree with you, having proper tags (on Github) and updated versions on npm would be great.

**Pull request merged**
