### PR TITLE
Added bower support

### PR DESCRIPTION
**Pull request by thedotmack**
Was pretty easy, ran bower init and it took care of all the heavy lifting. Next up is to register it once the bower.json is added to the repo:

`bower register <my-package-name> <git-endpoint>`

Details on how this is all done are here: https://bower.io/docs/creating-packages/

### CODE REVIEW

**Comment by moeamaya** [comment]
I'll be working on PRs later this week. Thx for the work Alex!

**Comment by acki** [comment]
@moeamaya Plz merge this one!
@thedotmack Thx for your work 😃

**Comment by moeamaya** [comment]
Ended up creating our own, although it's the same lol

**Comment by acki** [comment]
@moeamaya You have to look more often into Github ;)

**Pull request closed without merging**
